config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :businesses do
    resources :stories, only: [:new, :create]
  end
  resources :stories, only: [:edit, :update, :destroy, :show, :index]
  resources :creators
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  belongs_to :user
  has_many :stories, dependent: :destroy
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :story
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :creator_categories, dependent: :destroy
  has_many :creators, through: :creator_categories

  has_many :story_categories, dependent: :destroy
  has_many :stories, through: :story_categories
end

app/models/creator.rb
class Creator < ApplicationRecord
  belongs_to :user
  has_many :creator_categories, dependent: :destroy
  has_many :categories, through: :creator_categories
end

app/models/creator_category.rb
class CreatorCategory < ApplicationRecord
  belongs_to :creator
  belongs_to :category
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :business
  has_many :story_categories, dependent: :destroy
  has_many :categories, through: :story_categories
  has_many :campaigns, dependent: :destroy
end

app/models/story_category.rb
class StoryCategory < ApplicationRecord
  belongs_to :story
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :businesses, dependent: :destroy
  has_one :creator, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  def show
    @business = Business.find(params[:id])
  end

  def index
    @businesses = Business.where(user: current_user)
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.user = current_user
    if @business.save
      redirect_to business_path(@business)
    else
      render :new
    end
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    if @business.update(business_params)
      redirect_to business_path(@business)
    else
      render :edit
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :description, :website)
  end

  def set_business
    @business = Business.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_business, only: [:new, :create]
  before_action :set_story, only: [:edit, :update, :destroy, :show]


  def show
  end

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.business = @business

    params[:story][:category_ids].shift
    params[:story][:category_ids].each do |category_id|
      @story.categories << Category.find(category_id)
    end

    if @story.save
      redirect_to story_path(@story)
    else
      @story = Story.new
      render :new
    end
  end

  def edit
  end

  def update
    if @story.update(story_params)

      @story.categories.destroy_all
      params[:story][:category_ids].shift
      params[:story][:category_ids].each do |category_id|
        @story.categories << Category.find(category_id)
      end

      redirect_to story_path(@story)
    else
      set_story
      render :edit
    end
  end

  private

  def story_params
    params.require(:story).permit(:title, :description, :published)
  end

  def set_story
    @story = Story.find(params[:id])
  end

  def set_business
    @business = Business.find(params[:business_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/edit.html.erb
<h1>Businesses#edit</h1>
<%= simple_form_for(@business) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :website %>
  <%= f.submit "Update!" %>
<% end %>

app/views/businesses/index.html.erb
<h1>Businesses#index</h1>

<ul>
  <% @businesses.each do |business| %>
    <li>
      <p><%= link_to business.name, business_path(business) %></p>
    </li>
  <% end %>
</ul>

app/views/businesses/new.html.erb
<h1>Businesses#new</h1>
<%= simple_form_for(@business) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :website %>
  <%= f.submit "Create!" %>
<% end %>

app/views/businesses/show.html.erb
<h1>Businesses#show</h1>
<h2><%= @business.name %></h2>
<h3><%= @business.description %></h3>
<%= link_to "Create a Story for #{@business.name}", new_business_story_path(@business) %>
<%= link_to "Edit Business Info", edit_business_path(@business) %>

<ul>
  <% @business.stories.each do |story| %>
    <li>
      <p><%= link_to story.title, story_path(story) %></p>
      <p><%= story.categories.first.name %></p>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryDeck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>LANDING PAGE STUFF</h1>
<%= link_to "Sign Up", new_user_registration_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Businesses", businesses_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%= link_to "Businesses", businesses_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/stories/edit.html.erb
<h1>Stories#edit</h1>
<%= simple_form_for(@story) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :published %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  <%= f.submit "Update!" %>
<% end %>

app/views/stories/index.html.erb
<h1>Stories#Index</h1>

<% @stories.each do |story| %>
  <h2><%= story.title %></h2>
  <h3><%= story.description %></h3>


  <ul>
    <% story.categories.each do |category| %>
      <li>
        <%= category.name %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/stories/new.html.erb
<h1>Stories#new</h1>
<%= simple_form_for [@business, @story] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :published %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  <%= f.submit "Create!" %>
<% end %>

app/views/stories/show.html.erb
<h1>Stories#show</h1>
<h2><%= @story.title %></h2>
<h3><%= @story.description %></h3>
<%= link_to "Edit Story Info!", edit_story_path(@story) %>

<ul>
  <% @story.categories.each do |category| %>
    <li>
      <%= category.name %>
    </li>
  <% end %>
</ul>